In [26]:
from sklearn.datasets import make_regression as dummy_data
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [27]:
"""
creating the dummy_data for multiple_linear_regression 
n_samples =  tells the number of rows that should be there 
n_feature =  tells the number of column that should be there 
n_informative = tells how many columns ( which we created ) will effect the target 
n_target tells =  how many output column should be there 
noise = tells how much error should be there , as when the algo will find the line/plane how much error it will have from the point
"""

# result unpacking
x,y = dummy_data(n_samples=1000,n_features=4, n_informative=3 , n_targets=1 , noise=70 )

In [28]:
#df = pd.DataFrame(x, columns=['column1', 'column2', 'column3', 'column4'])
#df['target'] = y

In [29]:
# another way to make the data frame
df[['column1', 'column2', 'column3', 'column4']] = x.copy()
df["target"] = y
df

      column2   column3   column4      target   column1
0    0.211000 -0.338221  0.025530   45.276526  1.836093
1   -1.784404  1.337598  1.988703   92.984505  0.615708
2    0.091802 -1.156903 -1.678655   18.188924  0.752754
3   -0.773062  1.493303  0.216081   87.038761 -0.276270
4    0.697239 -0.537328 -2.061350  -30.095707  0.535747
..        ...       ...       ...         ...       ...
995  1.402413  0.321753 -1.218743  114.758758 -0.270807
996 -1.797333 -0.001392  0.670486  -19.766411  0.925671
997 -0.389826 -2.987677  0.010294  -35.135659  1.399168
998 -1.210280  0.264695 -0.407282   88.866267 -0.701608
999  1.879801  0.955664  1.137856   50.907371 -0.641147

[1000 rows x 5 columns]

In [30]:
print(df)

      column2   column3   column4      target   column1
0    0.211000 -0.338221  0.025530   45.276526  1.836093
1   -1.784404  1.337598  1.988703   92.984505  0.615708
2    0.091802 -1.156903 -1.678655   18.188924  0.752754
3   -0.773062  1.493303  0.216081   87.038761 -0.276270
4    0.697239 -0.537328 -2.061350  -30.095707  0.535747
..        ...       ...       ...         ...       ...
995  1.402413  0.321753 -1.218743  114.758758 -0.270807
996 -1.797333 -0.001392  0.670486  -19.766411  0.925671
997 -0.389826 -2.987677  0.010294  -35.135659  1.399168
998 -1.210280  0.264695 -0.407282   88.866267 -0.701608
999  1.879801  0.955664  1.137856   50.907371 -0.641147

[1000 rows x 5 columns]

# 3d ploting the graph 

as it is more easy to understand the data

In [31]:
px.scatter_3d(df , x ='column1',y= 'column4', z= 'target' )

## performing the linear rigression

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [33]:
x_train , x_test , y_train , y_test = train_test_split(df[['column1', 'column2', 'column3', 'column4']],df[["target"]],test_size=0.3,random_state=42)

In [34]:
lr = LinearRegression()

In [35]:
lr.fit(x_train , y_train)

LinearRegression()

In [36]:
lr.coef_ # column 1 has coef is near 0 means this column is no use

array([[49.01545357, 11.54009657, 49.46633454, -0.45392545]])

In [37]:
y_pred = lr.predict(x_test)

In [38]:
from sklearn.metrics import r2_score

In [39]:
r2_result = r2_score(y_true=y_test,y_pred=y_pred)
print(r2_result)

0.48298205402494043

code to drop the column from the dataframe

In [40]:
df =df.drop(columns=["column1"]) # droping the column 2 as is not helpful in finding the plane for linear regression

In [41]:
df

      column2   column3   column4      target
0    0.211000 -0.338221  0.025530   45.276526
1   -1.784404  1.337598  1.988703   92.984505
2    0.091802 -1.156903 -1.678655   18.188924
3   -0.773062  1.493303  0.216081   87.038761
4    0.697239 -0.537328 -2.061350  -30.095707
..        ...       ...       ...         ...
995  1.402413  0.321753 -1.218743  114.758758
996 -1.797333 -0.001392  0.670486  -19.766411
997 -0.389826 -2.987677  0.010294  -35.135659
998 -1.210280  0.264695 -0.407282   88.866267
999  1.879801  0.955664  1.137856   50.907371

[1000 rows x 4 columns]