In [254]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ankushpanday1/india-house-price-prediction")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\adity\.cache\kagglehub\datasets\ankushpanday1\india-house-price-prediction\versions\1

In [255]:
import pandas as pd
import numpy as np

In [256]:
import os
print(os.listdir(path))

['india_housing_prices.csv']

In [257]:
df = pd.read_csv("C:\\Users\\adity\\.cache\\kagglehub\\datasets\\ankushpanday1\\india-house-price-prediction\\versions\\1\\india_housing_prices.csv")

In [258]:
df.head(2)

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction

In [259]:
df.info() # just getting the idea how is this data set is stuctured

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              250000 non-null  int64
 1   State                           250000 non-null  object
 2   City                            250000 non-null  object
 3   Locality                        250000 non-null  object
 4   Property_Type                   250000 non-null  object
 5   BHK                             250000 non-null  int64
 6   Size_in_SqFt                    250000 non-null  int64
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64
 10  Furnished_Status                250000 non-null  object
 11  Floor_No                        250000 non-null  int64
 12  Total_Floors                    250000 non-null  int64
 13  Age_of_Property                 250000 non-null  int64
 14  Nearby_Schools                  250000 non-null  int64
 15  Nearby_Hospitals                250000 non-null  int64
 16  Public_Transport_Accessibility  250000 non-null  object
 17  Parking_Space                   250000 non-null  object
 18  Security                        250000 non-null  object
 19  Amenities                       250000 non-null  object
 20  Facing                          250000 non-null  object
 21  Owner_Type                      250000 non-null  object
 22  Availability_Status             250000 non-null  object
dtypes: float64(2), int64(9), object(12)
memory usage: 43.9+ MB

In [260]:
df.isnull().sum() # means there is no null values

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64

In [261]:
print(df.loc[df["State"]=="Maharashtra"])

            ID        State    City      Locality      Property_Type  BHK  \
1            2  Maharashtra    Pune  Locality_490  Independent House    3
12          13  Maharashtra  Nagpur  Locality_227  Independent House    3
18          19  Maharashtra    Pune  Locality_385              Villa    3
27          28  Maharashtra    Pune  Locality_143          Apartment    5
128        129  Maharashtra  Nagpur  Locality_171  Independent House    3
...        ...          ...     ...           ...                ...  ...
249872  249873  Maharashtra  Mumbai  Locality_455              Villa    1
249888  249889  Maharashtra    Pune  Locality_260          Apartment    2
249942  249943  Maharashtra  Mumbai  Locality_245              Villa    3
249959  249960  Maharashtra    Pune  Locality_115              Villa    4
249967  249968  Maharashtra  Mumbai  Locality_261  Independent House    1

        Size_in_SqFt  Price_in_Lakhs  Price_per_SqFt  Year_Built  ...  \
1               2364          195.52            0.08        2008  ...
12              1976          486.29            0.25        2020  ...
18              2126           24.50            0.01        2013  ...
27              2346          404.23            0.17        2016  ...
128             3213          415.99            0.13        2012  ...
...              ...             ...             ...         ...  ...
249872          1052          228.34            0.22        2001  ...
249888           521          163.62            0.31        2009  ...
249942          4141          285.19            0.07        2023  ...
249959          1034          406.21            0.39        2007  ...
249967          3543          167.78            0.05        2004  ...

       Age_of_Property  Nearby_Schools  Nearby_Hospitals  \
1                   17               8                 1
12                   5               6                 6
18                  12               8                 1
27                   9               8                 7
128                 13               1                 4
...                ...             ...               ...
249872              24              10                 9
249888              16               7                 1
249942               2               1                 6
249959              18               7                 4
249967              21               3                 6

        Public_Transport_Accessibility  Parking_Space  Security  \
1                                  Low             No       Yes
12                              Medium             No       Yes
18                                 Low             No       Yes
27                                High             No       Yes
128                               High            Yes        No
...                                ...            ...       ...
249872                          Medium             No        No
249888                          Medium             No       Yes
249942                          Medium            Yes        No
249959                             Low             No        No
249967                          Medium            Yes       Yes

                                       Amenities Facing Owner_Type  \
1       Playground, Clubhouse, Pool, Gym, Garden  North    Builder
12              Clubhouse, Gym, Playground, Pool  North    Builder
18      Garden, Clubhouse, Pool, Gym, Playground   West      Owner
27           Garden, Playground, Pool, Clubhouse  South      Owner
128                Playground, Gym, Pool, Garden  North    Builder
...                                          ...    ...        ...
249872  Gym, Clubhouse, Playground, Garden, Pool  North    Builder
249888                   Clubhouse, Pool, Garden   West      Owner
249942                                    Garden  North    Builder
249959                                Playground  North    Builder
249967                        Garden, Playground   East      Owner

       Availability_Status
1       Under_Construction
12           Ready_to_Move
18      Under_Construction
27           Ready_to_Move
128          Ready_to_Move
...                    ...
249872       Ready_to_Move
249888  Under_Construction
249942  Under_Construction
249959  Under_Construction
249967       Ready_to_Move

[12533 rows x 23 columns]

# checking how many states are there in this dataframe

In [262]:
print(df["State"].value_counts()) # value with its number of frequency
print(df["State"].nunique()) # gives how unique value is present

State
Odisha            12681
Tamil Nadu        12629
West Bengal       12622
Gujarat           12578
Delhi             12552
Telangana         12539
Maharashtra       12533
Punjab            12516
Uttar Pradesh     12508
Uttarakhand       12501
Assam             12496
Kerala            12487
Jharkhand         12480
Andhra Pradesh    12462
Chhattisgarh      12456
Madhya Pradesh    12451
Karnataka         12424
Rajasthan         12402
Bihar             12369
Haryana           12314
Name: count, dtype: int64
20

now i know there is data of 20 states ( unique) and how many rows are there for each row.

now i am tring to separate the data state wise .. do that i can work upon them seprately

### seperating the data state wise

In [263]:
df_delhi = df[df["State"]=="Delhi"].copy()
print(df_delhi)

            ID  State       City      Locality      Property_Type  BHK  \
8            9  Delhi  New Delhi  Locality_232              Villa    4
13          14  Delhi  New Delhi  Locality_287  Independent House    1
36          37  Delhi     Dwarka  Locality_480  Independent House    2
48          49  Delhi     Dwarka  Locality_273              Villa    2
55          56  Delhi  New Delhi  Locality_484          Apartment    2
...        ...    ...        ...           ...                ...  ...
249972  249973  Delhi  New Delhi  Locality_176  Independent House    5
249985  249986  Delhi  New Delhi  Locality_449          Apartment    3
249986  249987  Delhi     Dwarka  Locality_127              Villa    5
249989  249990  Delhi     Dwarka  Locality_208              Villa    1
249992  249993  Delhi     Dwarka   Locality_83          Apartment    1

        Size_in_SqFt  Price_in_Lakhs  Price_per_SqFt  Year_Built  ...  \
8               2678          189.16            0.07        2003  ...
13              1369          309.82            0.23        2013  ...
36               775           26.99            0.03        2008  ...
48              1771          335.78            0.19        2009  ...
55              3300          274.47            0.08        2010  ...
...              ...             ...             ...         ...  ...
249972          1644          341.21            0.21        2000  ...
249985          4789          200.48            0.04        1993  ...
249986          3890          360.63            0.09        1996  ...
249989          4802          245.29            0.05        1992  ...
249992          3408          225.27            0.07        2003  ...

       Age_of_Property  Nearby_Schools  Nearby_Hospitals  \
8                   22               7                 5
13                  12              10                 6
36                  17               8                 1
48                  16              10                 4
55                  15               9                10
...                ...             ...               ...
249972              25              10                 2
249985              32              10                 4
249986              29               2                 6
249989              33               8                 5
249992              22               9                 4

        Public_Transport_Accessibility  Parking_Space  Security  \
8                                  Low             No       Yes
13                              Medium             No        No
36                                High             No       Yes
48                              Medium            Yes       Yes
55                              Medium            Yes       Yes
...                                ...            ...       ...
249972                            High            Yes        No
249985                            High             No       Yes
249986                            High            Yes        No
249989                             Low             No       Yes
249992                             Low            Yes       Yes

                                       Amenities Facing Owner_Type  \
8                  Garden, Clubhouse, Playground  South     Broker
13      Clubhouse, Garden, Gym, Playground, Pool  South     Broker
36                                     Clubhouse  South     Broker
48                            Playground, Garden   West     Broker
55                    Clubhouse, Gym, Playground  South    Builder
...                                          ...    ...        ...
249972                Gym, Playground, Clubhouse   West    Builder
249985          Clubhouse, Playground, Pool, Gym  South      Owner
249986               Clubhouse, Pool, Playground  South     Broker
249989                         Gym, Pool, Garden  North     Broker
249992  Pool, Playground, Gym, Garden, Clubhouse   East    Builder

       Availability_Status
8       Under_Construction
13      Under_Construction
36           Ready_to_Move
48      Under_Construction
55           Ready_to_Move
...                    ...
249972  Under_Construction
249985  Under_Construction
249986       Ready_to_Move
249989       Ready_to_Move
249992       Ready_to_Move

[12552 rows x 23 columns]

# reseted the id and index values

In [264]:
df_delhi["ID"] = np.arange(0,len(df_delhi))
df_delhi.reset_index(inplace=True,drop=True)

## feature Engineering

In [265]:
df_delhi.head()

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,0,Delhi,New Delhi,Locality_232,Villa,4,2678,189.16,0.07,2003,...,22,7,5,Low,No,Yes,"Garden, Clubhouse, Playground",South,Broker,Under_Construction
1,1,Delhi,New Delhi,Locality_287,Independent House,1,1369,309.82,0.23,2013,...,12,10,6,Medium,No,No,"Clubhouse, Garden, Gym, Playground, Pool",South,Broker,Under_Construction
2,2,Delhi,Dwarka,Locality_480,Independent House,2,775,26.99,0.03,2008,...,17,8,1,High,No,Yes,Clubhouse,South,Broker,Ready_to_Move
3,3,Delhi,Dwarka,Locality_273,Villa,2,1771,335.78,0.19,2009,...,16,10,4,Medium,Yes,Yes,"Playground, Garden",West,Broker,Under_Construction
4,4,Delhi,New Delhi,Locality_484,Apartment,2,3300,274.47,0.08,2010,...,15,9,10,Medium,Yes,Yes,"Clubhouse, Gym, Playground",South,Builder,Ready_to_Move

In [266]:
df_delhi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12552 entries, 0 to 12551
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID                              12552 non-null  int64
 1   State                           12552 non-null  object
 2   City                            12552 non-null  object
 3   Locality                        12552 non-null  object
 4   Property_Type                   12552 non-null  object
 5   BHK                             12552 non-null  int64
 6   Size_in_SqFt                    12552 non-null  int64
 7   Price_in_Lakhs                  12552 non-null  float64
 8   Price_per_SqFt                  12552 non-null  float64
 9   Year_Built                      12552 non-null  int64
 10  Furnished_Status                12552 non-null  object
 11  Floor_No                        12552 non-null  int64
 12  Total_Floors                    12552 non-null  int64
 13  Age_of_Property                 12552 non-null  int64
 14  Nearby_Schools                  12552 non-null  int64
 15  Nearby_Hospitals                12552 non-null  int64
 16  Public_Transport_Accessibility  12552 non-null  object
 17  Parking_Space                   12552 non-null  object
 18  Security                        12552 non-null  object
 19  Amenities                       12552 non-null  object
 20  Facing                          12552 non-null  object
 21  Owner_Type                      12552 non-null  object
 22  Availability_Status             12552 non-null  object
dtypes: float64(2), int64(9), object(12)
memory usage: 2.2+ MB

In [267]:
df_delhi.isnull().sum()

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64

### updating object type into the data type

In [268]:
for col in df_delhi.columns:
    print("column name = ", col)
    print("data inside a column =",df_delhi[col])
    print("\n\n--new column--\n\n\n")

column name =  ID
data inside a column = 0            0
1            1
2            2
3            3
4            4
         ...
12547    12547
12548    12548
12549    12549
12550    12550
12551    12551
Name: ID, Length: 12552, dtype: int64


--new column--



column name =  State
data inside a column = 0        Delhi
1        Delhi
2        Delhi
3        Delhi
4        Delhi
         ...
12547    Delhi
12548    Delhi
12549    Delhi
12550    Delhi
12551    Delhi
Name: State, Length: 12552, dtype: object


--new column--



column name =  City
data inside a column = 0        New Delhi
1        New Delhi
2           Dwarka
3           Dwarka
4        New Delhi
           ...
12547    New Delhi
12548    New Delhi
12549       Dwarka
12550       Dwarka
12551       Dwarka
Name: City, Length: 12552, dtype: object


--new column--



column name =  Locality
data inside a column = 0        Locality_232
1        Locality_287
2        Locality_480
3        Locality_273
4        Locality_484
             ...
12547    Locality_176
12548    Locality_449
12549    Locality_127
12550    Locality_208
12551     Locality_83
Name: Locality, Length: 12552, dtype: object


--new column--



column name =  Property_Type
data inside a column = 0                    Villa
1        Independent House
2        Independent House
3                    Villa
4                Apartment
               ...
12547    Independent House
12548            Apartment
12549                Villa
12550                Villa
12551            Apartment
Name: Property_Type, Length: 12552, dtype: object


--new column--



column name =  BHK
data inside a column = 0        4
1        1
2        2
3        2
4        2
        ..
12547    5
12548    3
12549    5
12550    1
12551    1
Name: BHK, Length: 12552, dtype: int64


--new column--



column name =  Size_in_SqFt
data inside a column = 0        2678
1        1369
2         775
3        1771
4        3300
         ...
12547    1644
12548    4789
12549    3890
12550    4802
12551    3408
Name: Size_in_SqFt, Length: 12552, dtype: int64


--new column--



column name =  Price_in_Lakhs
data inside a column = 0        189.16
1        309.82
2         26.99
3        335.78
4        274.47
          ...
12547    341.21
12548    200.48
12549    360.63
12550    245.29
12551    225.27
Name: Price_in_Lakhs, Length: 12552, dtype: float64


--new column--



column name =  Price_per_SqFt
data inside a column = 0        0.07
1        0.23
2        0.03
3        0.19
4        0.08
         ...
12547    0.21
12548    0.04
12549    0.09
12550    0.05
12551    0.07
Name: Price_per_SqFt, Length: 12552, dtype: float64


--new column--



column name =  Year_Built
data inside a column = 0        2003
1        2013
2        2008
3        2009
4        2010
         ...
12547    2000
12548    1993
12549    1996
12550    1992
12551    2003
Name: Year_Built, Length: 12552, dtype: int64


--new column--



column name =  Furnished_Status
data inside a column = 0        Semi-furnished
1           Unfurnished
2        Semi-furnished
3        Semi-furnished
4        Semi-furnished
              ...
12547    Semi-furnished
12548    Semi-furnished
12549         Furnished
12550       Unfurnished
12551         Furnished
Name: Furnished_Status, Length: 12552, dtype: object


--new column--



column name =  Floor_No
data inside a column = 0        23
1        13
2        11
3        26
4         0
         ..
12547    10
12548    27
12549    17
12550    26
12551    20
Name: Floor_No, Length: 12552, dtype: int64


--new column--



column name =  Total_Floors
data inside a column = 0        16
1         4
2        14
3        19
4        28
         ..
12547     9
12548     7
12549     7
12550    10
12551    15
Name: Total_Floors, Length: 12552, dtype: int64


--new column--



column name =  Age_of_Property
data inside a column = 0        22
1        12
2        17
3        16
4        15
         ..
12547    25
12548    32
12549    29
12550    33
12551    22
Name: Age_of_Property, Length: 12552, dtype: int64


--new column--



column name =  Nearby_Schools
data inside a column = 0         7
1        10
2         8
3        10
4         9
         ..
12547    10
12548    10
12549     2
12550     8
12551     9
Name: Nearby_Schools, Length: 12552, dtype: int64


--new column--



column name =  Nearby_Hospitals
data inside a column = 0         5
1         6
2         1
3         4
4        10
         ..
12547     2
12548     4
12549     6
12550     5
12551     4
Name: Nearby_Hospitals, Length: 12552, dtype: int64


--new column--



column name =  Public_Transport_Accessibility
data inside a column = 0           Low
1        Medium
2          High
3        Medium
4        Medium
          ...
12547      High
12548      High
12549      High
12550       Low
12551       Low
Name: Public_Transport_Accessibility, Length: 12552, dtype: object


--new column--



column name =  Parking_Space
data inside a column = 0         No
1         No
2         No
3        Yes
4        Yes
        ...
12547    Yes
12548     No
12549    Yes
12550     No
12551    Yes
Name: Parking_Space, Length: 12552, dtype: object


--new column--



column name =  Security
data inside a column = 0        Yes
1         No
2        Yes
3        Yes
4        Yes
        ...
12547     No
12548    Yes
12549     No
12550    Yes
12551    Yes
Name: Security, Length: 12552, dtype: object


--new column--



column name =  Amenities
data inside a column = 0                   Garden, Clubhouse, Playground
1        Clubhouse, Garden, Gym, Playground, Pool
2                                       Clubhouse
3                              Playground, Garden
4                      Clubhouse, Gym, Playground
                           ...
12547                  Gym, Playground, Clubhouse
12548            Clubhouse, Playground, Pool, Gym
12549                 Clubhouse, Pool, Playground
12550                           Gym, Pool, Garden
12551    Pool, Playground, Gym, Garden, Clubhouse
Name: Amenities, Length: 12552, dtype: object


--new column--



column name =  Facing
data inside a column = 0        South
1        South
2        South
3         West
4        South
         ...
12547     West
12548    South
12549    South
12550    North
12551     East
Name: Facing, Length: 12552, dtype: object


--new column--



column name =  Owner_Type
data inside a column = 0         Broker
1         Broker
2         Broker
3         Broker
4        Builder
          ...
12547    Builder
12548      Owner
12549     Broker
12550     Broker
12551    Builder
Name: Owner_Type, Length: 12552, dtype: object


--new column--



column name =  Availability_Status
data inside a column = 0        Under_Construction
1        Under_Construction
2             Ready_to_Move
3        Under_Construction
4             Ready_to_Move
                ...
12547    Under_Construction
12548    Under_Construction
12549         Ready_to_Move
12550         Ready_to_Move
12551         Ready_to_Move
Name: Availability_Status, Length: 12552, dtype: object


--new column--

firstly encoding the locality , as locality plays a important role in deciding the price hence converting it into the number.

using the ---> target encoding <---

-> replacing the locality with its mean price.

In [269]:
df_delhi["Locality"].nunique() # total 5 hunderad new locality

500

In [270]:
df_delhi["Locality"].value_counts() # how many times thoes locality appeared in the data frame

Locality
Locality_407    40
Locality_441    38
Locality_463    38
Locality_157    38
Locality_129    37
                ..
Locality_36     13
Locality_343    12
Locality_435    11
Locality_162    11
Locality_353    10
Name: count, Length: 500, dtype: int64

In [271]:
result = df_delhi.groupby('Locality')["Price_in_Lakhs"].mean()
print(result)

Locality
Locality_1      266.822727
Locality_10     236.346667
Locality_100    273.157600
Locality_101    208.321471
Locality_102    266.048800
                   ...
Locality_95     277.520952
Locality_96     280.061765
Locality_97     329.645789
Locality_98     225.674194
Locality_99     270.831034
Name: Price_in_Lakhs, Length: 500, dtype: float64

In [272]:
df_delhi["Locality_encoded"] = df_delhi["Locality"].map(result)

In [273]:
df_delhi[["Locality","Locality_encoded"]].head()

       Locality  Locality_encoded
0  Locality_232        245.450000
1  Locality_287        256.282000
2  Locality_480        241.900968
3  Locality_273        267.341739
4  Locality_484        244.086538

In [274]:
df_delhi.drop(columns=['Locality'], inplace=True ,)

now changing the city column into numerical value

In [275]:
df_delhi['City'].nunique() # 2 unique vlaue
df_delhi['City'].value_counts()

City
New Delhi    6306
Dwarka       6246
Name: count, dtype: int64

In [276]:
df_delhi.replace(["New Delhi","Dwarka"],[0,1],inplace=True)
df_delhi['City'].head()

C:\Users\adity\AppData\Local\Temp\ipykernel_832\489722746.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_delhi.replace(["New Delhi","Dwarka"],[0,1],inplace=True)

0    0
1    0
2    1
3    1
4    0
Name: City, dtype: int64

now working on a property type

In [277]:
df_delhi['Property_Type'].value_counts()

Property_Type
Villa                4323
Independent House    4153
Apartment            4076
Name: count, dtype: int64

In [278]:
one_hot_encod = pd.get_dummies(df_delhi["Property_Type"], drop_first=True)
print(one_hot_encod)

       Independent House  Villa
0                  False   True
1                   True  False
2                   True  False
3                  False   True
4                  False  False
...                  ...    ...
12547               True  False
12548              False  False
12549              False   True
12550              False   True
12551              False  False

[12552 rows x 2 columns]

In [279]:
df_delhi = pd.concat([df_delhi,one_hot_encod],axis=1)
df_delhi.drop(columns=['Property_Type'],inplace=True)

In [280]:
df_delhi.drop(columns=['Year_Built'],inplace=True)

In [281]:
df_delhi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12552 entries, 0 to 12551
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID                              12552 non-null  int64
 1   State                           12552 non-null  object
 2   City                            12552 non-null  int64
 3   BHK                             12552 non-null  int64
 4   Size_in_SqFt                    12552 non-null  int64
 5   Price_in_Lakhs                  12552 non-null  float64
 6   Price_per_SqFt                  12552 non-null  float64
 7   Furnished_Status                12552 non-null  object
 8   Floor_No                        12552 non-null  int64
 9   Total_Floors                    12552 non-null  int64
 10  Age_of_Property                 12552 non-null  int64
 11  Nearby_Schools                  12552 non-null  int64
 12  Nearby_Hospitals                12552 non-null  int64
 13  Public_Transport_Accessibility  12552 non-null  object
 14  Parking_Space                   12552 non-null  object
 15  Security                        12552 non-null  object
 16  Amenities                       12552 non-null  object
 17  Facing                          12552 non-null  object
 18  Owner_Type                      12552 non-null  object
 19  Availability_Status             12552 non-null  object
 20  Locality_encoded                12552 non-null  float64
 21  Independent House               12552 non-null  bool
 22  Villa                           12552 non-null  bool
dtypes: bool(2), float64(3), int64(9), object(9)
memory usage: 2.0+ MB

In [282]:
df_delhi['Furnished_Status'].unique()
df_delhi['Public_Transport_Accessibility'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [283]:
df_delhi['Public_Transport_Accessibility'].replace(['Low', 'Medium', 'High'],[0,1,2],inplace=True)
df_delhi['Furnished_Status'].replace(['Semi-furnished', 'Unfurnished', 'Furnished'],[0,1,2],inplace=True)

C:\Users\adity\AppData\Local\Temp\ipykernel_832\149969118.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_delhi['Public_Transport_Accessibility'].replace(['Low', 'Medium', 'High'],[0,1,2],inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_832\149969118.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_delhi['Public_Transport_Accessibility'].replace(['Low', 'Medium', 'High'],[0,1,2],inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_832\149969118.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_delhi['Furnished_Status'].replace(['Semi-furnished', 'Unfurnished', 'Furnished'],[0,1,2],inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_832\149969118.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_delhi['Furnished_Status'].replace(['Semi-furnished', 'Unfurnished', 'Furnished'],[0,1,2],inplace=True)

In [284]:
print(df_delhi['Security'].unique())
print(df_delhi['Parking_Space'].unique())

['Yes' 'No']
['No' 'Yes']

In [285]:
df_delhi['Security'].replace(['Yes' ,'No'],[0,1],inplace=True)
df_delhi['Parking_Space'].replace(['Yes', 'No'],[0,1],inplace=True)

C:\Users\adity\AppData\Local\Temp\ipykernel_832\724683883.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_delhi['Security'].replace(['Yes' ,'No'],[0,1],inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_832\724683883.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_delhi['Security'].replace(['Yes' ,'No'],[0,1],inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_832\724683883.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_delhi['Parking_Space'].replace(['Yes', 'No'],[0,1],inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_832\724683883.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_delhi['Parking_Space'].replace(['Yes', 'No'],[0,1],inplace=True)

In [286]:
df_delhi.drop(columns=['Facing'],inplace=True)

In [287]:
print(df_delhi['Owner_Type'].unique())
print(df_delhi['Availability_Status'].unique())

['Broker' 'Builder' 'Owner']
['Under_Construction' 'Ready_to_Move']

In [288]:
diff_owner = pd.get_dummies(df['Owner_Type'],drop_first=True)
pd.concat([df_delhi,diff_owner],axis=1)
df_delhi.drop(columns=['Owner_Type'],inplace=True)

In [289]:
df_delhi['Availability_Status'].replace(['Under_Construction' ,'Ready_to_Move'],[0,1],inplace=True)

C:\Users\adity\AppData\Local\Temp\ipykernel_832\2580380385.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_delhi['Availability_Status'].replace(['Under_Construction' ,'Ready_to_Move'],[0,1],inplace=True)
C:\Users\adity\AppData\Local\Temp\ipykernel_832\2580380385.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_delhi['Availability_Status'].replace(['Under_Construction' ,'Ready_to_Move'],[0,1],inplace=True)

In [291]:
df_delhi.drop(columns=['ID','State','Price_per_SqFt'],inplace=True)

### now targeting the elephant of the room - aminities

In [292]:
df['Amenities'].value_counts()

Amenities
Pool                                        10218
Clubhouse                                   10010
Garden                                      10006
Gym                                          9938
Playground                                   9934
                                            ...
Playground, Gym, Clubhouse, Garden, Pool      369
Garden, Gym, Pool, Playground                 368
Pool, Garden, Clubhouse, Playground, Gym      367
Garden, Clubhouse, Pool, Gym                  360
Clubhouse, Pool, Garden, Playground, Gym      355
Name: count, Length: 325, dtype: int64

In [293]:
from sklearn.preprocessing import MultiLabelBinarizer

# Step 1 - convert string to list
df_delhi["Amenities"] = df_delhi["Amenities"].apply(lambda x: x.split(", "))

# Step 2 - apply MultiLabelBinarizer
mlb = MultiLabelBinarizer()
amenities_encoded = pd.DataFrame(
    mlb.fit_transform(df_delhi["Amenities"]),
    columns=mlb.classes_,
    index=df_delhi.index  # important to align indexes before concat!
)

# Step 3 - concat and drop original
df_delhi = pd.concat([df_delhi, amenities_encoded], axis=1)
df_delhi.drop("Amenities", axis=1, inplace=True)

## machine learnig algo

In [294]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [295]:
x = df_delhi.drop(columns=['Price_in_Lakhs'])
y = df_delhi['Price_in_Lakhs']

In [296]:
x_train , x_test , y_train , y_test = train_test_split(x, y , random_state=42 , test_size=0.3)

In [297]:
lr = LinearRegression()

In [298]:
lr.fit(x_train,y_train)

LinearRegression()

In [299]:
y_pred = lr.predict(x_test)

In [300]:
r2_score(y_pred=y_pred,y_true=y_test)

0.04753284619932485