In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ankushpanday1/india-house-price-prediction")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\adity\.cache\kagglehub\datasets\ankushpanday1\india-house-price-prediction\versions\1

In [2]:
import pandas as pd
import numpy as np

In [3]:
import os
print(os.listdir(path))

['india_housing_prices.csv']

In [4]:
df = pd.read_csv("C:\\Users\\adity\\.cache\\kagglehub\\datasets\\ankushpanday1\\india-house-price-prediction\\versions\\1\\india_housing_prices.csv")

In [5]:
df.head(2)

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction

In [6]:
df.info() # just getting the idea how is this data set is stuctured

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              250000 non-null  int64
 1   State                           250000 non-null  object
 2   City                            250000 non-null  object
 3   Locality                        250000 non-null  object
 4   Property_Type                   250000 non-null  object
 5   BHK                             250000 non-null  int64
 6   Size_in_SqFt                    250000 non-null  int64
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64
 10  Furnished_Status                250000 non-null  object
 11  Floor_No                        250000 non-null  int64
 12  Total_Floors                    250000 non-null  int64
 13  Age_of_Property                 250000 non-null  int64
 14  Nearby_Schools                  250000 non-null  int64
 15  Nearby_Hospitals                250000 non-null  int64
 16  Public_Transport_Accessibility  250000 non-null  object
 17  Parking_Space                   250000 non-null  object
 18  Security                        250000 non-null  object
 19  Amenities                       250000 non-null  object
 20  Facing                          250000 non-null  object
 21  Owner_Type                      250000 non-null  object
 22  Availability_Status             250000 non-null  object
dtypes: float64(2), int64(9), object(12)
memory usage: 43.9+ MB

In [7]:
df.isnull().sum() # means there is no null values

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64

In [8]:
print(df.loc[df["State"]=="Maharashtra"])

            ID        State    City      Locality      Property_Type  BHK  \
1            2  Maharashtra    Pune  Locality_490  Independent House    3
12          13  Maharashtra  Nagpur  Locality_227  Independent House    3
18          19  Maharashtra    Pune  Locality_385              Villa    3
27          28  Maharashtra    Pune  Locality_143          Apartment    5
128        129  Maharashtra  Nagpur  Locality_171  Independent House    3
...        ...          ...     ...           ...                ...  ...
249872  249873  Maharashtra  Mumbai  Locality_455              Villa    1
249888  249889  Maharashtra    Pune  Locality_260          Apartment    2
249942  249943  Maharashtra  Mumbai  Locality_245              Villa    3
249959  249960  Maharashtra    Pune  Locality_115              Villa    4
249967  249968  Maharashtra  Mumbai  Locality_261  Independent House    1

        Size_in_SqFt  Price_in_Lakhs  Price_per_SqFt  Year_Built  ...  \
1               2364          195.52            0.08        2008  ...
12              1976          486.29            0.25        2020  ...
18              2126           24.50            0.01        2013  ...
27              2346          404.23            0.17        2016  ...
128             3213          415.99            0.13        2012  ...
...              ...             ...             ...         ...  ...
249872          1052          228.34            0.22        2001  ...
249888           521          163.62            0.31        2009  ...
249942          4141          285.19            0.07        2023  ...
249959          1034          406.21            0.39        2007  ...
249967          3543          167.78            0.05        2004  ...

       Age_of_Property  Nearby_Schools  Nearby_Hospitals  \
1                   17               8                 1
12                   5               6                 6
18                  12               8                 1
27                   9               8                 7
128                 13               1                 4
...                ...             ...               ...
249872              24              10                 9
249888              16               7                 1
249942               2               1                 6
249959              18               7                 4
249967              21               3                 6

        Public_Transport_Accessibility  Parking_Space  Security  \
1                                  Low             No       Yes
12                              Medium             No       Yes
18                                 Low             No       Yes
27                                High             No       Yes
128                               High            Yes        No
...                                ...            ...       ...
249872                          Medium             No        No
249888                          Medium             No       Yes
249942                          Medium            Yes        No
249959                             Low             No        No
249967                          Medium            Yes       Yes

                                       Amenities Facing Owner_Type  \
1       Playground, Clubhouse, Pool, Gym, Garden  North    Builder
12              Clubhouse, Gym, Playground, Pool  North    Builder
18      Garden, Clubhouse, Pool, Gym, Playground   West      Owner
27           Garden, Playground, Pool, Clubhouse  South      Owner
128                Playground, Gym, Pool, Garden  North    Builder
...                                          ...    ...        ...
249872  Gym, Clubhouse, Playground, Garden, Pool  North    Builder
249888                   Clubhouse, Pool, Garden   West      Owner
249942                                    Garden  North    Builder
249959                                Playground  North    Builder
249967                        Garden, Playground   East      Owner

       Availability_Status
1       Under_Construction
12           Ready_to_Move
18      Under_Construction
27           Ready_to_Move
128          Ready_to_Move
...                    ...
249872       Ready_to_Move
249888  Under_Construction
249942  Under_Construction
249959  Under_Construction
249967       Ready_to_Move

[12533 rows x 23 columns]

# checking how many states are there in this dataframe

In [9]:
print(df["State"].value_counts()) # value with its number of frequency
print(df["State"].nunique()) # gives how unique value is present

State
Odisha            12681
Tamil Nadu        12629
West Bengal       12622
Gujarat           12578
Delhi             12552
Telangana         12539
Maharashtra       12533
Punjab            12516
Uttar Pradesh     12508
Uttarakhand       12501
Assam             12496
Kerala            12487
Jharkhand         12480
Andhra Pradesh    12462
Chhattisgarh      12456
Madhya Pradesh    12451
Karnataka         12424
Rajasthan         12402
Bihar             12369
Haryana           12314
Name: count, dtype: int64
20

now i know there is data of 20 states ( unique) and how many rows are there for each row.

now i am tring to separate the data state wise .. do that i can work upon them seprately

### seperating the data state wise

In [10]:
df_delhi = df[df["State"]=="Delhi"].copy()
print(df_delhi)

            ID  State       City      Locality      Property_Type  BHK  \
8            9  Delhi  New Delhi  Locality_232              Villa    4
13          14  Delhi  New Delhi  Locality_287  Independent House    1
36          37  Delhi     Dwarka  Locality_480  Independent House    2
48          49  Delhi     Dwarka  Locality_273              Villa    2
55          56  Delhi  New Delhi  Locality_484          Apartment    2
...        ...    ...        ...           ...                ...  ...
249972  249973  Delhi  New Delhi  Locality_176  Independent House    5
249985  249986  Delhi  New Delhi  Locality_449          Apartment    3
249986  249987  Delhi     Dwarka  Locality_127              Villa    5
249989  249990  Delhi     Dwarka  Locality_208              Villa    1
249992  249993  Delhi     Dwarka   Locality_83          Apartment    1

        Size_in_SqFt  Price_in_Lakhs  Price_per_SqFt  Year_Built  ...  \
8               2678          189.16            0.07        2003  ...
13              1369          309.82            0.23        2013  ...
36               775           26.99            0.03        2008  ...
48              1771          335.78            0.19        2009  ...
55              3300          274.47            0.08        2010  ...
...              ...             ...             ...         ...  ...
249972          1644          341.21            0.21        2000  ...
249985          4789          200.48            0.04        1993  ...
249986          3890          360.63            0.09        1996  ...
249989          4802          245.29            0.05        1992  ...
249992          3408          225.27            0.07        2003  ...

       Age_of_Property  Nearby_Schools  Nearby_Hospitals  \
8                   22               7                 5
13                  12              10                 6
36                  17               8                 1
48                  16              10                 4
55                  15               9                10
...                ...             ...               ...
249972              25              10                 2
249985              32              10                 4
249986              29               2                 6
249989              33               8                 5
249992              22               9                 4

        Public_Transport_Accessibility  Parking_Space  Security  \
8                                  Low             No       Yes
13                              Medium             No        No
36                                High             No       Yes
48                              Medium            Yes       Yes
55                              Medium            Yes       Yes
...                                ...            ...       ...
249972                            High            Yes        No
249985                            High             No       Yes
249986                            High            Yes        No
249989                             Low             No       Yes
249992                             Low            Yes       Yes

                                       Amenities Facing Owner_Type  \
8                  Garden, Clubhouse, Playground  South     Broker
13      Clubhouse, Garden, Gym, Playground, Pool  South     Broker
36                                     Clubhouse  South     Broker
48                            Playground, Garden   West     Broker
55                    Clubhouse, Gym, Playground  South    Builder
...                                          ...    ...        ...
249972                Gym, Playground, Clubhouse   West    Builder
249985          Clubhouse, Playground, Pool, Gym  South      Owner
249986               Clubhouse, Pool, Playground  South     Broker
249989                         Gym, Pool, Garden  North     Broker
249992  Pool, Playground, Gym, Garden, Clubhouse   East    Builder

       Availability_Status
8       Under_Construction
13      Under_Construction
36           Ready_to_Move
48      Under_Construction
55           Ready_to_Move
...                    ...
249972  Under_Construction
249985  Under_Construction
249986       Ready_to_Move
249989       Ready_to_Move
249992       Ready_to_Move

[12552 rows x 23 columns]

# reseted the id and index values

In [12]:
df_delhi["ID"] = np.arange(0,len(df_delhi))
df_delhi.reset_index(inplace=True,drop=True)

## feature Engineering

In [13]:
df_delhi.head()

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,0,Delhi,New Delhi,Locality_232,Villa,4,2678,189.16,0.07,2003,...,22,7,5,Low,No,Yes,"Garden, Clubhouse, Playground",South,Broker,Under_Construction
1,1,Delhi,New Delhi,Locality_287,Independent House,1,1369,309.82,0.23,2013,...,12,10,6,Medium,No,No,"Clubhouse, Garden, Gym, Playground, Pool",South,Broker,Under_Construction
2,2,Delhi,Dwarka,Locality_480,Independent House,2,775,26.99,0.03,2008,...,17,8,1,High,No,Yes,Clubhouse,South,Broker,Ready_to_Move
3,3,Delhi,Dwarka,Locality_273,Villa,2,1771,335.78,0.19,2009,...,16,10,4,Medium,Yes,Yes,"Playground, Garden",West,Broker,Under_Construction
4,4,Delhi,New Delhi,Locality_484,Apartment,2,3300,274.47,0.08,2010,...,15,9,10,Medium,Yes,Yes,"Clubhouse, Gym, Playground",South,Builder,Ready_to_Move

In [15]:
df_delhi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12552 entries, 0 to 12551
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ID                              12552 non-null  int64
 1   State                           12552 non-null  object
 2   City                            12552 non-null  object
 3   Locality                        12552 non-null  object
 4   Property_Type                   12552 non-null  object
 5   BHK                             12552 non-null  int64
 6   Size_in_SqFt                    12552 non-null  int64
 7   Price_in_Lakhs                  12552 non-null  float64
 8   Price_per_SqFt                  12552 non-null  float64
 9   Year_Built                      12552 non-null  int64
 10  Furnished_Status                12552 non-null  object
 11  Floor_No                        12552 non-null  int64
 12  Total_Floors                    12552 non-null  int64
 13  Age_of_Property                 12552 non-null  int64
 14  Nearby_Schools                  12552 non-null  int64
 15  Nearby_Hospitals                12552 non-null  int64
 16  Public_Transport_Accessibility  12552 non-null  object
 17  Parking_Space                   12552 non-null  object
 18  Security                        12552 non-null  object
 19  Amenities                       12552 non-null  object
 20  Facing                          12552 non-null  object
 21  Owner_Type                      12552 non-null  object
 22  Availability_Status             12552 non-null  object
dtypes: float64(2), int64(9), object(12)
memory usage: 2.2+ MB

In [16]:
df_delhi.isnull().sum()

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64